### ISSUE TITLE
tests failed on localnet

### ISSUE THREAD

**Issue by fallenangel2305** [Aurory-Game/comptoir#12]
comptoir with mint
https://solscan.io/token/4WvVtVhrAvK9wsYmwgtu6f7YFpfbNJKHvSm9PXH2LPVd
Transaction simulation failed: Attempt to load a program that does not exist 
    
    1) Prepare tests variables
    ✔ create comptoir (242ms)
Transaction simulation failed: Error processing Instruction 0: custom program error: 0x1770 
    Program pgmjwHMQM9j2Q1jjwbv7y746dtzp28c3DnHoiXbhHL8 invoke [1]
    Program log: Instruction: CreateComptoir
    Program 11111111111111111111111111111111 invoke [2]
    Program 11111111111111111111111111111111 success
    Program 11111111111111111111111111111111 invoke [2]
    Program 11111111111111111111111111111111 success
    Program TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA invoke [2]
    Program log: Instruction: InitializeAccount
    Program TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA consumed 3347 of 1383332 compute units
    Program TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA success
    Program log: Custom program error: 0x1770
    Program pgmjwHMQM9j2Q1jjwbv7y746dtzp28c3DnHoiXbhHL8 consumed 28473 of 1400000 compute units
    Program pgmjwHMQM9j2Q1jjwbv7y746dtzp28c3DnHoiXbhHL8 failed: custom program error: 0x1770
    ✔ fail: create comptoir fee > 10000 (878ms)
    ✔ update comptoir fields (1571ms)
    ✔ update comptoir mint (1677ms)
    ✔ create collection (412ms)
Transaction simulation failed: Error processing Instruction 0: custom program error: 0x0 
    Program pgmjwHMQM9j2Q1jjwbv7y746dtzp28c3DnHoiXbhHL8 invoke [1]
    Program log: Instruction: CreateCollection
    Program 11111111111111111111111111111111 invoke [2]
    Allocate: account Address { address: 4Mscm6p66z8JBzySHKHkPJx45AfyaKWka4u3BdNxfssh, base: None } already in use
    Program 11111111111111111111111111111111 failed: custom program error: 0x0
    Program pgmjwHMQM9j2Q1jjwbv7y746dtzp28c3DnHoiXbhHL8 consumed 5546 of 1400000 compute units
    Program pgmjwHMQM9j2Q1jjwbv7y746dtzp28c3DnHoiXbhHL8 failed: custom program error: 0x0
    ✔ fail: create collection fee > 10000 (44ms)
    ✔ update collection (788ms)
    2) create sell order
    3) remove one item from sell order
    4) add one item to sell order
    5) buy the nft

  ignore creators tests
https://solscan.io/token/CmZ5RGbWvViTxFpTvEwA3eGjU2mLdUiM2yLHKfv5PFLZ
Transaction simulation failed: Attempt to load a program that does not exist 
    
    6) Prepare tests variables
    7) sell order ignore creators

  comptoir with mint
https://solscan.io/token/CKFA8sXBmGdwjKLvPNHQyvcZt2k8hTVsXuLxASJbAwb8
Transaction simulation failed: Attempt to load a program that does not exist 
    
    8) Prepare tests variables
    9) remove nft offer
    10) create nft offer
    11) execute nft offer

  multi sell orders test
https://solscan.io/token/ECqRmZv73XejEqkKA7ojaT1HBhnR37ZERyodfLPMPyXF
Transaction simulation failed: Attempt to load a program that does not exist 
    
    12) Prepare tests variables
    13) sell and buy multiple orders

  7 passing (17s)
  13 failing

  1) comptoir with mint
       Prepare tests variables:
     Error: failed to send transaction: Transaction simulation failed: Attempt to load a program that does not exist
      at Connection.sendEncodedTransaction (node_modules/@solana/web3.js/src/connection.ts:3689:13)
      at processTicksAndRejections (node:internal/process/task_queues:96:5)
      at Connection.sendRawTransaction (node_modules/@solana/web3.js/src/connection.ts:3649:20)
      at sendAndConfirmRawTransaction (node_modules/@solana/web3.js/src/util/send-and-confirm-raw-transaction.ts:27:21)
      at Provider.send (node_modules/@project-serum/anchor/src/provider.ts:118:18)

  2) comptoir with mint
       create sell order:
     TypeError: Cannot read properties of undefined (reading 'publicKey')
      at /home/mvp/Desktop/blockchain/comptoir/tests/comptoir.ts:385:35
      at Generator.next (<anonymous>)
      at /home/mvp/Desktop/blockchain/comptoir/tests/comptoir.ts:27:71
      at new Promise (<anonymous>)
      at __awaiter (tests/comptoir.ts:23:12)
      at Context.<anonymous> (tests/comptoir.ts:374:40)
      at processImmediate (node:internal/timers:466:21)

  3) comptoir with mint
       remove one item from sell order:
     Error: Invalid arguments: sellerNftTokenAccount not provided.
      at /home/mvp/Desktop/blockchain/comptoir/node_modules/@project-serum/anchor/src/program/common.ts:50:15
      at Array.forEach (<anonymous>)
      at validateAccounts (node_modules/@project-serum/anchor/src/program/common.ts:45:14)
      at ix (node_modules/@project-serum/anchor/src/program/namespace/instruction.ts:44:23)
      at txFn (node_modules/@project-serum/anchor/src/program/namespace/transaction.ts:24:14)
      at Object.rpc [as removeSellOrder] (node_modules/@project-serum/anchor/src/program/namespace/rpc.ts:22:18)
      at /home/mvp/Desktop/blockchain/comptoir/tests/comptoir.ts:410:27
      at Generator.next (<anonymous>)
      at /home/mvp/Desktop/blockchain/comptoir/tests/comptoir.ts:27:71
      at new Promise (<anonymous>)
      at __awaiter (tests/comptoir.ts:23:12)
      at Context.<anonymous> (tests/comptoir.ts:407:54)
      at processImmediate (node:internal/timers:466:21)

  4) comptoir with mint
       add one item to sell order:
     Error: Invalid arguments: sellerNftTokenAccount not provided.
      at /home/mvp/Desktop/blockchain/comptoir/node_modules/@project-serum/anchor/src/program/common.ts:50:15
      at Array.forEach (<anonymous>)
      at validateAccounts (node_modules/@project-serum/anchor/src/program/common.ts:45:14)
      at ix (node_modules/@project-serum/anchor/src/program/namespace/instruction.ts:44:23)
      at txFn (node_modules/@project-serum/anchor/src/program/namespace/transaction.ts:24:14)
      at Object.rpc [as addQuantityToSellOrder] (node_modules/@project-serum/anchor/src/program/namespace/rpc.ts:22:18)
      at /home/mvp/Desktop/blockchain/comptoir/tests/comptoir.ts:434:27
      at Generator.next (<anonymous>)
      at /home/mvp/Desktop/blockchain/comptoir/tests/comptoir.ts:27:71
      at new Promise (<anonymous>)
      at __awaiter (tests/comptoir.ts:23:12)
      at Context.<anonymous> (tests/comptoir.ts:431:49)
      at processImmediate (node:internal/timers:466:21)

  5) comptoir with mint
       buy the nft:
     TypeError: Cannot read properties of undefined (reading 'getOrCreateAssociatedAccountInfo')
      at /home/mvp/Desktop/blockchain/comptoir/tests/comptoir.ts:462:41
      at Generator.next (<anonymous>)
      at fulfilled (tests/comptoir.ts:24:58)
      at processTicksAndRejections (node:internal/process/task_queues:96:5)

  6) ignore creators tests
       Prepare tests variables:
     Error: failed to send transaction: Transaction simulation failed: Attempt to load a program that does not exist
      at Connection.sendEncodedTransaction (node_modules/@solana/web3.js/src/connection.ts:3689:13)
      at processTicksAndRejections (node:internal/process/task_queues:96:5)
      at Connection.sendRawTransaction (node_modules/@solana/web3.js/src/connection.ts:3649:20)
      at sendAndConfirmRawTransaction (node_modules/@solana/web3.js/src/util/send-and-confirm-raw-transaction.ts:27:21)
      at Provider.send (node_modules/@project-serum/anchor/src/provider.ts:118:18)

  7) ignore creators tests
       sell order ignore creators:
     TypeError: Cannot read properties of undefined (reading 'sellAsset')
      at Context.<anonymous> (tests/ignore_creators.ts:92:26)
      at Generator.next (<anonymous>)
      at /home/mvp/Desktop/blockchain/comptoir/tests/ignore_creators.ts:27:71
      at new Promise (<anonymous>)
      at __awaiter (tests/ignore_creators.ts:23:12)
      at Context.<anonymous> (tests/ignore_creators.ts:83:16)
      at processImmediate (node:internal/timers:466:21)

  8) comptoir with mint
       Prepare tests variables:
     Error: failed to send transaction: Transaction simulation failed: Attempt to load a program that does not exist
      at Connection.sendEncodedTransaction (node_modules/@solana/web3.js/src/connection.ts:3689:13)
      at processTicksAndRejections (node:internal/process/task_queues:96:5)
      at Connection.sendRawTransaction (node_modules/@solana/web3.js/src/connection.ts:3649:20)
      at sendAndConfirmRawTransaction (node_modules/@solana/web3.js/src/util/send-and-confirm-raw-transaction.ts:27:21)
      at Provider.send (node_modules/@project-serum/anchor/src/provider.ts:118:18)

  9) comptoir with mint
       remove nft offer:
     TypeError: Cannot read properties of undefined (reading 'publicKey')
      at /home/mvp/Desktop/blockchain/comptoir/tests/offer.ts:192:38
      at Generator.next (<anonymous>)
      at /home/mvp/Desktop/blockchain/comptoir/tests/offer.ts:27:71
      at new Promise (<anonymous>)
      at __awaiter (tests/offer.ts:23:12)
      at Context.<anonymous> (tests/offer.ts:187:39)
      at processImmediate (node:internal/timers:466:21)

  10) comptoir with mint
       create nft offer:
     TypeError: Cannot read properties of undefined (reading 'publicKey')
      at /home/mvp/Desktop/blockchain/comptoir/tests/offer.ts:240:38
      at Generator.next (<anonymous>)
      at /home/mvp/Desktop/blockchain/comptoir/tests/offer.ts:27:71
      at new Promise (<anonymous>)
      at __awaiter (tests/offer.ts:23:12)
      at Context.<anonymous> (tests/offer.ts:235:39)
      at processImmediate (node:internal/timers:466:21)

  11) comptoir with mint
       execute nft offer:
     Error: Invalid arguments: destination not provided.
      at /home/mvp/Desktop/blockchain/comptoir/node_modules/@project-serum/anchor/src/program/common.ts:50:15
      at Array.forEach (<anonymous>)
      at validateAccounts (node_modules/@project-serum/anchor/src/program/common.ts:45:14)
      at ix (node_modules/@project-serum/anchor/src/program/namespace/instruction.ts:44:23)
      at txFn (node_modules/@project-serum/anchor/src/program/namespace/transaction.ts:24:14)
      at Object.rpc [as executeOffer] (node_modules/@project-serum/anchor/src/program/namespace/rpc.ts:22:18)
      at /home/mvp/Desktop/blockchain/comptoir/tests/offer.ts:272:27
      at Generator.next (<anonymous>)
      at /home/mvp/Desktop/blockchain/comptoir/tests/offer.ts:27:71
      at new Promise (<anonymous>)
      at __awaiter (tests/offer.ts:23:12)
      at Context.<anonymous> (tests/offer.ts:271:40)
      at processImmediate (node:internal/timers:466:21)

  12) multi sell orders test
       Prepare tests variables:
     Error: failed to send transaction: Transaction simulation failed: Attempt to load a program that does not exist
      at Connection.sendEncodedTransaction (node_modules/@solana/web3.js/src/connection.ts:3689:13)
      at processTicksAndRejections (node:internal/process/task_queues:96:5)
      at Connection.sendRawTransaction (node_modules/@solana/web3.js/src/connection.ts:3649:20)
      at sendAndConfirmRawTransaction (node_modules/@solana/web3.js/src/util/send-and-confirm-raw-transaction.ts:27:21)
      at Provider.send (node_modules/@project-serum/anchor/src/provider.ts:118:18)

  13) multi sell orders test
       sell and buy multiple orders:
     TypeError: Cannot read properties of undefined (reading 'sellAsset')
      at Context.<anonymous> (tests/sell_orders.ts:90:26)
      at Generator.next (<anonymous>)
      at /home/mvp/Desktop/blockchain/comptoir/tests/sell_orders.ts:27:71
      at new Promise (<anonymous>)
      at __awaiter (tests/sell_orders.ts:23:12)
      at Context.<anonymous> (tests/sell_orders.ts:82:16)
      at processImmediate (node:internal/timers:466:21)

error Command failed with exit code 13.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by ceciEstErmat** [comment]
Hi,

So what manipulation have you done to get such a result ?
Just an anchor test ?
What is your anchor cli version ?

**Comment by ceciEstErmat** [comment]
Since right now we are on the v23 of anchor make sur your cli matches this :)

**Comment by fallenangel2305** [comment]
anchor-cli 0.23.0

**Comment by fallenangel2305** [comment]
I just ran anchor test after build and deploy

**Comment by fallenangel2305** [comment]
plz add docs on how to use the program

**Comment by ceciEstErmat** [comment]
A full write up is coming in the next few week. We are right now focusing on sending that to production
